[project]
name = "unit-converter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "streamlit>=1.43.0",
]

[tool.uv.workspace]
members = ["unit-converter", "unit-converter/unit-converter"]
